version = 1
type = "contexts"
description = "One-off import of Historic Environment Scotland West data"
format = "csv"

[column.HES_ID]
target = "source_id"

[column.SiteName]
target = "name"

[column.Latitude]
target = "geometry:lat"

[column.Longitude]
target = "geometry:lng"
